runtime: python27
api_version: 1
version: 1
application: chirp-api
threadsafe: true
handlers:
- url: /register
  script: register.app
- url: /EmailComfirm
  script: EmailComfirm.app
- url: /Login
  script: Login.app
- url: /CreateEvent
  script: CreateEvent.app